// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3YNqMxn2QUGID6F6bJGpxV7SsxWnwYCM',
    appId: '1:509949769802:web:e584e3d7060f3b7552ceb3',
    messagingSenderId: '509949769802',
    projectId: 'soulnote-b44be',
    authDomain: 'soulnote-b44be.firebaseapp.com',
    storageBucket: 'soulnote-b44be.firebasestorage.app',
    measurementId: 'G-V579Y44RWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wFHnuSkHwi3H5A8AvKaQ_r25j6QMO0s',
    appId: '1:509949769802:android:ebb36bf02b6f147952ceb3',
    messagingSenderId: '509949769802',
    projectId: 'soulnote-b44be',
    storageBucket: 'soulnote-b44be.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3YNqMxn2QUGID6F6bJGpxV7SsxWnwYCM',
    appId: '1:509949769802:web:42c7ddc672614a6152ceb3',
    messagingSenderId: '509949769802',
    projectId: 'soulnote-b44be',
    authDomain: 'soulnote-b44be.firebaseapp.com',
    storageBucket: 'soulnote-b44be.firebasestorage.app',
    measurementId: 'G-3N12DYS15Z',
  );
}
